context.modules = [{
	name = libpipewire-module-loopback
	args = {
		audio.position = [ FL FR ]
		capture.props = {
			node.name = "gameSpeaker"
			node.description = "gameSpeaker"
			media.class = "Audio/Sink"
			node.autoconnect = false
		}
		playback.props = {
			node.name = "gameOutput"
			node.description = "gameOutput"
		}
	}
}]
