# termux sets TERM to screen-256color by default, which breaks backward/forward-word
set -g default-terminal tmux-256color

set -g default-client-command "new -A"

set -g history-limit 20000
bind-key -T copy-mode C-S-Home send -X history-top # Ctrl+Shift+Home
bind-key -T copy-mode C-S-End send -X history-bottom # Ctrl+Shift+End

# pane border
set -g pane-border-status top
set -g pane-border-format " [ #D #{?pane_input_off,(ro),}#T ] "

# status bar
set -g status-style 'fg=black #{?client_prefix,bg=red,bg=green}' # make red if prefix pressed

# new-window starts at current pane working directory
bind c new-window -c "#{pane_current_path}"
bind \" split-window -c "#{pane_current_path}"

# set current panel to read-only,read-write
set -ga command-alias ropanel='selectp -d'
set -ga command-alias rwpanel='selectp -e'

set -ga command-alias keepp='set -p remain-on-exit on'
