#!/bin/nft -f
flush ruleset

# mostly copied from https://wiki.archlinux.org/title/Nftables#Simple_stateful_firewall
table inet main {
	set LANv4 {
		type ipv4_addr
		flags interval

		elements = { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 169.254.0.0/16 }
	}
	set LANv6 {
		type ipv6_addr
		flags interval

		elements = { fd00::/8, fe80::/10 }
	}

	set allowed_any { type inet_service; flags interval; }
	set allowed_tcp { type inet_service; flags interval; }
	set allowed_udp { type inet_service; flags interval; }

	chain input {
		type filter hook input priority filter
		policy drop

		# accept related and estabilished traffic
		ct state established,related accept

		# accept all from loopback interface
		iif "lo" accept

		# drop invalid traffic
		ct state invalid drop

		# accept all icmp, igmp
		meta l4proto { ipv6-icmp, icmp } accept
		ip protocol igmp accept

		ct state != new drop

		meta l4proto {tcp, udp} th dport @allowed_any accept
		udp dport @allowed_udp accept
		tcp flags & (fin | syn | rst | ack) == syn tcp dport @allowed_tcp accept

		# LAN
		ip6 saddr @LANv6 jump lan
		ip saddr @LANv4 jump lan
	}

	set allowed_any_lan { type inet_service; flags interval; }
	set allowed_tcp_lan { type inet_service; flags interval; }
	set allowed_udp_lan { type inet_service; flags interval; }

	chain lan {
		meta l4proto {tcp, udp} th dport @allowed_any_lan accept
		udp dport @allowed_udp_lan accept
		tcp flags & (fin | syn | rst | ack) == syn tcp dport @allowed_tcp_lan accept
	}

	chain output {
		type filter hook output priority filter
		policy accept
	}


	chain forward {
		type filter hook forward priority filter
		policy drop

		# accept related and estabilished traffic
		ct state established,related accept
	}

	chain postrouting {
		type nat hook postrouting priority filter
	}
}

include "/etc/nftables.conf.d/*"
