include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"

# The server clause sets the main parameters.
server:
	verbosity: 1

	tls-system-cert: yes

	interface: 0.0.0.0
	interface: ::
	access-control: 0.0.0.0/0 allow
	access-control: ::/0 allow

	trust-anchor-file: "/etc/unbound/trusted-key.key"

	prefetch: yes

	serve-expired: yes
	serve-expired-ttl: 172800  # between 86400 (1 day) and 259200 (3 days)
	serve-expired-client-timeout: 1800  # RFC 8767 recommended value

	#log-queries: yes

	include: "/etc/unbound/blocklists.d/*.conf"

forward-zone:
	name: "."
	forward-tls-upstream: yes
	forward-addr: 94.140.15.15@853#dns.adguard-dns.com
