[global]
	http-only
	i: fd:3,10.99.112.2
	rproxy: 1

	#ftpv
	ftp: 990
	ftp-pr: 65500-65520

	hist: /var/lib/copyparty/hist
	dav-inf
	no-acode
	ah-alg: argon2
	th-mt: 1
	idp-adm: mat
	exp
	js-other: /.extra/index.js
	acao: moz-extension://4978d76f-387b-43f0-afc0-271039644f2d,*

% ./rest.conf
